USE [master]
GO
/****** Object:  Database [Respaldo]    Script Date: 24/02/2020 11:30:22 p. m. ******/
DROP DATABASE IF EXISTS [Respaldo]
GO
/****** Object:  Database [Respaldo]    Script Date: 24/02/2020 11:30:22 p. m. ******/
CREATE DATABASE [Respaldo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Respaldo', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Respaldo.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Respaldo_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Respaldo_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [Respaldo] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Respaldo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Respaldo] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Respaldo] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Respaldo] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Respaldo] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Respaldo] SET ARITHABORT OFF 
GO
ALTER DATABASE [Respaldo] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Respaldo] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Respaldo] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Respaldo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Respaldo] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Respaldo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Respaldo] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Respaldo] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Respaldo] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Respaldo] SET  ENABLE_BROKER 
GO
ALTER DATABASE [Respaldo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Respaldo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Respaldo] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Respaldo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Respaldo] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Respaldo] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Respaldo] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Respaldo] SET RECOVERY FULL 
GO
ALTER DATABASE [Respaldo] SET  MULTI_USER 
GO
ALTER DATABASE [Respaldo] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Respaldo] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Respaldo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Respaldo] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Respaldo] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'Respaldo', N'ON'
GO
ALTER DATABASE [Respaldo] SET QUERY_STORE = OFF
GO
ALTER DATABASE [Respaldo] SET  READ_WRITE 
GO
